### ISSUE TITLE
Group assigment

### ISSUE THREAD

**Issue by dvatri** [redminenb/redminenb#40]
It would be great to have possibility of issue assignment to groups. And search issues assigned to user group.

**Comment by matthiasblaesing** [comment]
Could you please give this test version a spin:

https://github.com/redminenb/redminenb/wiki/redminenb-1.10.1-SNAPSHOT.nbm

it should cover most changes necessary. Internally it is a bit improvised, but that should not stop you :-)

**Comment by dvatri** [comment]
Thank you! 1.10.1 thows an exception and Assignee list currently empty (1.10 works fine for me).

java.lang.NullPointerException
	at com.kenai.redminenb.util.AssigneeWrapper.<init>(AssigneeWrapper.java:32)
	at com.kenai.redminenb.repository.RedmineRepository.getAssigneeWrappers(RedmineRepository.java:498)
	at com.kenai.redminenb.issue.RedmineIssuePanel.initProjectData(RedmineIssuePanel.java:559)
	at com.kenai.redminenb.issue.RedmineIssuePanel.initIssue(RedmineIssuePanel.java:531)
	at com.kenai.redminenb.issue.RedmineIssueController$2.run(RedmineIssueController.java:90)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by matthiasblaesing** [comment]
I think this should do it:

https://github.com/redminenb/redminenb/wiki/redminenb-1.10.2-SNAPSHOT.nbm

**Comment by dvatri** [comment]
Thank you! Works great! Group assigment and even search query.
