### ISSUE TITLE
DEFECT A JSONObject text must begin with '{' at character 1 if server answer 301

### ISSUE THREAD

**Issue by svatos-jirka** [redminenb/redminenb#52]
Hi,

during creation new issue I got:

org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.taskadapter.redmineapi.internal.RedmineJSONParser.getResponseSingleObject(RedmineJSONParser.java:534)
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:596)
Caused: com.taskadapter.redmineapi.RedmineFormatException
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:598)
	at com.taskadapter.redmineapi.internal.Transport.addChildEntry(Transport.java:258)
	at com.taskadapter.redmineapi.ProjectManager.createVersion(ProjectManager.java:153)
[catch] at com.kenai.redminenb.issue.RedmineIssuePanel.addVersion(RedmineIssuePanel.java:1742)
	at com.kenai.redminenb.issue.RedmineIssuePanel.access$1600(RedmineIssuePanel.java:107)
	at com.kenai.redminenb.issue.RedmineIssuePanel$17.run(RedmineIssuePanel.java:1732)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
WARNING [com.kenai.redminenb.issue.RedmineIssuePanel]: Can't create Redmine issue
org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.taskadapter.redmineapi.internal.RedmineJSONParser.getResponseSingleObject(RedmineJSONParser.java:534)
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:596)
Caused: com.taskadapter.redmineapi.RedmineFormatException
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:598)
	at com.taskadapter.redmineapi.internal.Transport.addObject(Transport.java:231)
	at com.taskadapter.redmineapi.IssueManager.createIssue(IssueManager.java:155)
	at com.kenai.redminenb.issue.RedmineIssuePanel$6.doInBackground(RedmineIssuePanel.java:822)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)

Request from wireshark: (it seems good)
{
  "issue": {
    "subject": "JiriS",
    "parent_issue_id": null,
    "estimated_hours": null,
    "assigned_to_id": 1975,
    "priority_id": 4,
    "done_ratio": 50,
    "project_id": 886,
    "start_date": "2016-11-28",
    "due_date": "2016-12-03",
    "tracker_id": 7,
    "description": "Editor:\n\t- backend part\n\t- CRUD project\n\t- CRUD station in project\n\t- based on Spring MVC 4.0.5, code generator wdt-generator\n\n",
    "status_id": 1,
    "fixed_version_id": null,
    "category_id": null
  }
}

server response:
Hypertext Transfer Protocol
    HTTP/1.1 301 Moved Permanently\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 301 Moved Permanently\r\n]
            [HTTP/1.1 301 Moved Permanently\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Version: HTTP/1.1
        Status Code: 301
        Response Phrase: Moved Permanently
    Date: Wed, 30 Nov 2016 10:54:54 GMT\r\n
    Server: Apache\r\n
    Location: https://xxx.com/redmine/issues.json?include=attachments\r\n
    Content-Length: 282\r\n
        [Content length: 282]
    Keep-Alive: timeout=15, max=2000\r\n
    Connection: Keep-Alive\r\n
    Content-Type: text/html; charset=iso-8859-1\r\n
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.023744000 seconds]
    [Request in frame: 76]
    File Data: 282 bytes
Line-based text data: text/html

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://xxx.com/redmine/issues.json?include=attachments">here</a>.</p>

It seems, that client tries to parse 301 answer instead of redirect,

with best regards, Jiri

**Comment by matthiasblaesing** [comment]
If someone wants to have a look at this:
- `com.taskadapter.redmineapi.internal.comm.redmine.RedmineErrorHandler` should be adjusted to report non 2?? status codes to the user (currently only special errors are reported - see https://github.com/taskadapter/redmine-java-api/issues/277)
- HttpClient can be advised to follow redirects in any situation (POSTs are not eligible for automatic redirect handling), it could be implemented in the repository configuration to allow redirects
